name: Deploy to Windows Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clean and clone repo
        run: |
          # Remove old directory if it exists (force removal)
          if exist "C:\Projects\CIT-Windows-Server-Documentation" (
            rmdir /s /q "C:\Projects\CIT-Windows-Server-Documentation"
          )
          # Clone fresh copy
          git clone https://github.com/Antigro09/CIT-Windows-Server-Documentation.git "C:\Projects\CIT-Windows-Server-Documentation"
