name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Mark the project folder as safe
      - name: Mark project folder as safe
        run: git config --global --add safe.directory "C:/Projects/CIT-Windows-Server-Documentation"

      # Checkout the repository code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Clean destination folder and reinitialize
      - name: Clean destination folder
        run: |
          Remove-Item -Recurse -Force "C:\Projects\CIT-Windows-Server-Documentation\*" 
          git init
          git remote add origin https://github.com/Antigro09/CIT-Windows-Server-Documentation.git
          git pull origin main
