name: Deploy to Windows Server

on:
  push:
    branches:
      - main  # Or whatever your deployment branch is

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Clean the target folder before copying (ensure no leftover files)
      - name: Clean destination folder
        run: Remove-Item -Recurse -Force "C:\Projects\CIT-Windows-Server-Documentation\*" 

      # Step 3: Copy the files to the desired destination folder
      - name: Copy files to C:\Projects
        run: |
          robocopy C:\actions-runner\_work\CIT-Windows-Server-Documentation\CIT-Windows-Server-Documentation C:\Projects\CIT-Windows-Server-Documentation /MIR
