name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Mark project folder as safe
        run: git config --global --add safe.directory "C:/Projects/CIT-Windows-Server-Documentation"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to local folder
        run: |
          cd C:\Projects\CIT-Windows-Server-Documentation
          git pull origin main
