name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Fix permissions for SSH directory
        shell: powershell
        run: |
          $sshPath = "C:\Users\Administrator\.ssh"
          if (Test-Path $sshPath) {
              icacls $sshPath /grant Administrator:F /T
          } else {
              Write-Host "$sshPath does not exist. Please check the path."
          }

      - name: Configure SSH and deploy
        shell: powershell
        run: |
          # Configure Git to use your SSH key
          git config --global core.sshCommand "ssh -i C:/Users/Administrator/.ssh/id_ed25519 -o StrictHostKeyChecking=no"
          git config --global --add safe.directory "C:/Projects/CIT-Windows-Server-Documentation"

          # Add GitHub to known hosts if needed
          if (!(Test-Path "C:\Users\Administrator\.ssh\known_hosts")) {
            ssh-keyscan github.com >> C:\Users\Administrator\.ssh\known_hosts
          }

          # Pull if repo exists, clone if not
          if (Test-Path "C:\Projects\CIT-Windows-Server-Documentation\.git") {
            Set-Location -Path "C:\Projects\CIT-Windows-Server-Documentation"
            git pull origin main
          } else {
            git clone git@github.com:Antigro09/CIT-Windows-Server-Documentation.git C:\Projects\CIT-Windows-Server-Documentation
          }
