name: Deploy to Windows Server

on:
  push:
    branches:
      - main  # Or your deployment branch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to local folder
        run: |
          cd C:\Projects\CIT-Windows-Server-Documentation
          git pull origin main
