name: Deploy to Windows Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clean and clone repo
        shell: powershell
        run: |
          # Ensure SSH is working correctly
          Write-Host "Testing SSH connection to GitHub..."
          ssh -T git@github.com -o StrictHostKeyChecking=no
          
          # Check if directory exists
          if (Test-Path "C:\Projects\CIT-Windows-Server-Documentation\.git") {
            # Repository exists, pull updates
            Set-Location -Path "C:\Projects\CIT-Windows-Server-Documentation"
            git pull origin main
          } else {
            # Repository doesn't exist, clone it
            if (Test-Path "C:\Projects\CIT-Windows-Server-Documentation") {
              # Clean up existing directory if it's not a git repo
              Remove-Item -Path "C:\Projects\CIT-Windows-Server-Documentation\*" -Recurse -Force
            } else {
              New-Item -ItemType Directory -Path "C:\Projects\CIT-Windows-Server-Documentation" -Force
            }
            
            # Clone using SSH
            Set-Location -Path "C:\Projects"
            git clone git@github.com:Antigro09/CIT-Windows-Server-Documentation.git
          }
